default_platform(:ios)

platform :ios do
    lane :test do
        xcversion(version: "~> 12.0")
        Dir.chdir("..") do
            Action.sh("xcodebuild -resolvePackageDependencies")
        end
        scan
    end
end
