default_platform(:ios)

platform :ios do
    lane :carthage_swift do
        run_lane("Carthage", "test")
    end

    lane :carthage_objc do
        run_lane("CarthageObjC", "test")
    end

    lane :cocoapods_swift do
        run_lane("CocoaPods", "test")
    end

    lane :cocoapods_objc do
        run_lane("CocoaPodsObjC", "test")
    end

    lane :swift_package_manager do
        run_lane("SwiftPackageManager", "test")
    end

    lane :binary_framework_swift do
        git_submodule_update
        run_lane("line-sdk-ios-swift", "xcframework")
        run_lane("BinaryFramework", "test")
    end

    lane :binary_framework_objc do
        git_submodule_update
        run_lane("line-sdk-ios-swift", "xcframework")
        run_lane("BinaryFrameworkObjC", "test")
    end
end

def run_lane(folder, lane)
    Dir.chdir("../#{folder}") do
        Action.sh("bundle exec fastlane #{lane}")
    end
end