# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CocoaPodsObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPods
  pod 'LineSDKSwift/ObjC', '~> 5.0'

  target 'CocoaPodsObjCTests' do
    inherit! :search_paths
  end
end
